### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ssh352** [bspeice/libaeron-sys#8]
I cloned the repo and run `cargo build`

`
  --- stderr
  CMake Error: The source directory "/home/ssh/Documents/code/bspeice/libaeron-sys/libaeron_driver-sys/aeron" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
`

won't build on MacOs 13,  could you advise what is supposed to be in libaeron_driver-sys/aeron? Thanks!

**Comment by ssh352** [comment]
I got it: the aeron dir should be aeron repo root dir.

**Comment by bspeice** [comment]
The aeron directory is a git submodule; when cloning, please make sure to also `git submodule update --init --recursive`. If you're still having problems building once that's been initialized, please let me know.

**Comment by bspeice** [comment]
Set up an OSX VM and upgraded to 1.40.0, this still compiles correctly. Let me know if you're still having problems.

**Comment by ssh352** [comment]
Thank you, this crate is really useful.
